### ISSUE TITLE
치지직연결은 잘 되지만 아프리카에 대해서는 웹소켓이 끊겼다는 경고가 뜹니다.

### ISSUE THREAD

**Issue by Kimsch05n** [taromati/done-connector#2]
같은 조건이지만 치지직 측만 연결이 됩니다.

**Comment by Kimsch05n** [comment]
peper_1.20.1_196 테스트 기준으로 
아프리카측 웹소켓 커넥팅이 문제가 있는 것 같습니다.

방송이 켜져있지않은 경우엔 "아프리카 TV 채팅에 연결 중 오류가 발생했습니다."라며 치지직만 연결 된 상태로 서버가 켜지며,

방송이 켜져있는 경우에는 "아프리카 TV 웹소켓 연결이 끊겼습니다." 라고 뜹니다.

![스크린샷 2024-06-17 004527](https://github.com/taromati/done-connector/assets/172927427/95b2b96e-c62b-4ddc-8907-c2ddc3bcb360)
![스크린샷 2024-06-17 004447](https://github.com/taromati/done-connector/assets/172927427/e83eda06-832f-4e41-ab5b-ec4e8a178c49)

**Comment by taromati** [comment]
아프리카쪽 웹소캣 프로토콜이 변경된거 같네요
패킷 분석부터 다시 해야할거라 당분간은 사용이 어렵습니다

**Comment by Kimsch05n** [comment]
정말 혹시나 실례지만 개인적으로 문의드릴 메시지 수단이 있을까용?..

**Comment by taromati** [comment]
taromati@taromati.me 로 메일 주세요

**Comment by taromati** [comment]
프로토콜이 바뀐게 아니라 인증 쪽 문제여서 바로 수정 됐네요 1.7.0 받아서 실행해주세요 동작 테스트는 완료 했습니다.
