### ISSUE TITLE
1.20버젼 이하는 안되는건가요??

### ISSUE THREAD

**Issue by NoteBlockMR** [taromati/done-connector#3]
나중에 1.19버젼이나 1.18버젼으로 시도해보고싶은데 될까요??
API에는 1.20버젼으로 적혀있던데

**Comment by taromati** [comment]
1.18까지 버전 호환 추가는 했는데 테스트는 안됐습니다 직접 1.7.1 받아서 테스트 부탁드립니다

**Comment by NoteBlockMR** [comment]
18.06 05:23:43 [Server] ERROR [LegacyPluginLoadingStrategy] Could not load 'plugins/done-connector-1.7.1.jar' in folder 'plugins'
18.06 05:23:43 [Server] INFO org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
18.06 05:23:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:382) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at io.papermc.paper.plugin.entrypoint.strategy.LegacyPluginLoadingStrategy.loadProviders(LegacyPluginLoadingStrategy.java:202) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
18.06 05:23:43 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]

이거 plugin.yml파일 열어서 직접 수정해야되나요??

**Comment by taromati** [comment]
로그상으로는 서버가 1.20을 지원하지 않는다고 나오는데 사용하신 서버 종류 및 버전 등 정보를 알려주세요

**Comment by taromati** [comment]
최초 한번 실행시에는 config.yml이 없어 오류가 한번 나면서 파일이 생성되고 그 이후에 파일을 직접 수정하여 스트리머 정보를 입력하셔야합니다

**Comment by NoteBlockMR** [comment]
그냥 1.19.4버젼을 사용중입니다만 plugin.yml 파일 열어서 1.19로 수정했더니 구동 되네요

**Comment by taromati** [comment]
아 말씀하신 부분에서 누락이 있었네요 수정해서 1.7.2 버전으로 업데이트 했습니다. 직접 수정하신거 쓰셔도 되고 새로 받으셔도 됩니다
