### ISSUE TITLE
1.21버젼 지원 부탁드립니다!!

### ISSUE THREAD

**Issue by NoteBlockMR** [taromati/done-connector#4]
1.21 버젼 시도하니까 에러가 출력합니다
구동될수있게 해주실수 있을까요??

**Comment by taromati** [comment]
마인크래프트 1.21 버전 지원 추가한 1.7.3 버전 새로 올렸습니다.
1.21은 자바버전 17 지원이 끊겨 자바버전을 21로 올렸습니다.
release에서 새로 다운받아서 이용해주세요.
