### ISSUE TITLE
아프리카 방송인 닉네임이 #으로 시작하는 경우

### ISSUE THREAD

**Issue by Yuupering** [taromati/done-connector#6]
이 경우에는 어떻게 처리 해야 될까요?
식별자에 #를 달면 주석 처리가 되는건가요?

**Comment by Yuupering** [comment]
추가적으로 치지직 닉네임에 띄어 쓰기가 포함 되는 경우는 식별자를 어떻게 작성해야 될까요? 띄어쓰기 포함해서 작성하면 될까요?

**Comment by taromati** [comment]
식별자가 #으로 시작할 경우 ""로 감싸면 됩니다. 
예를들어 다음과 같이 #이든 띄어쓰기든 ""로 감싸주면 동작 합니다.
아프리카:
  "#타로 마티":
    식별자: "#taro mati"
    마크닉네임: taromati
    
<img width="741" alt="스크린샷 2024-10-14 오전 10 17 46" src="https://github.com/user-attachments/assets/6c238177-fe77-402e-b811-0c86efa60857">
