### ISSUE TITLE
스트리머 개별 로드 기능을 추가 해주실수 있으실까요?

### ISSUE THREAD

**Issue by Yuupering** [taromati/done-connector#7]
현재 서버에 등록된 스트리머가 대략 40명쯤 되는 상황입니다. done reconnect 를 사용하게 된다면 TPS가 급락하게 되며 렉이 걸리게 됩니다.

따로 서버에 on join을 하게 된다면 스크립트상으로 처리하고 싶은데 done reconnect 기능을 분할 시켜주실수 있을까요?

예시
/done reconnect all : 서버 전체 등록된 스트리머 재연결
/done reconnect Yuupe1234 : Yuupe1234 마인크래프트 아이디에 등록된 방송 재연결

**Comment by taromati** [comment]
예시대로 추가해서 1.8.0 release 했습니다.

**Comment by Yuupering** [comment]
혹시...자바 버전 17 버전 업데이트 한번 해주실수 있으실까요?
